Identification
WildCodeSchool/lille-0920-js-p3-pema-backend pull request #1
Opened 2021-01-26 08:44 UTC by ThomasMlh

2021-01-26 10:00 UTC, Sarahshr approved these changes, later dismissed
It's ok for me !

2021-01-27 08:10 UTC, LoicBrassart requested changes
Many useless code bits, please clean it

2021-01-27 08:10 UTC, LoicBrassart commented on passport-strategies.js
> +        console.log(e);
Nope, no `console.log`

2021-01-27 08:10 UTC, LoicBrassart commented on routes/auth.js
> +  console.log(token);
Nope, delete this line

2021-01-27 08:10 UTC, LoicBrassart commented on routes/misc.js
> +    "Welcome on Authentication-101! Feel free to read the README.md file";
You probably don't need this message, do you ? ;-)

2021-01-27 08:10 UTC, LoicBrassart commented on routes/misc.js
> +    "If you can see this, you should be logged in, " + req.user.firstname;
Same here

2021-01-27 08:10 UTC, LoicBrassart commented on server.js
> +  console.warn(msg);
Nope

2021-01-27 09:08 UTC, Sarahshr approved these changes
It's good for me !

2021-01-27 09:22 UTC, LoicBrassart approved these changes
NmE

2021-01-27 09:51 UTC, merged