Routes
WildCodeSchool/lille-0920-js-p3-pema-backend pull request #2
Opened 2021-02-02 15:40 UTC by Sarahshr

2021-02-02 20:42 UTC, ThomasMlh requested changes
Let's back to work !

2021-02-02 20:42 UTC, ThomasMlh commented on routes/chapters.js
> +  console.log(timeline[0]);
```suggestion
```
No no no ! Remove it !

2021-02-02 20:42 UTC, ThomasMlh commented on routes/chapters.js
> +    console.log(req.body);
```suggestion
```
Arf !

2021-02-02 20:42 UTC, ThomasMlh commented on routes/chapters.js
> +  console.log(id);
```suggestion
```
?????

2021-02-02 20:42 UTC, ThomasMlh commented on routes/chapters.js
> +    console.log(err);
```suggestion
```
OMG !!!

2021-02-02 20:42 UTC, ThomasMlh commented on routes/chapters.js
> +  console.log(req.body);
```suggestion
```
Hello there !

2021-02-02 20:42 UTC, ThomasMlh commented on routes/chapters.js
> +    console.log(err);
```suggestion
```
Wow...

2021-02-02 20:42 UTC, ThomasMlh commented on server.js
>  });
```suggestion
```
Maybe it's useless no ? And again a console.log ! 
Maybe you should remove this route

2021-02-02 21:05 UTC, ThomasMlh approved these changes
It's ok 👍

2021-02-04 10:15 UTC, LoicBrassart approved these changes
SnE
(Good reviews bu ThomM, by the way !)

2021-02-04 10:15 UTC, LoicBrassart commented on package.json
> +    "mysql2-promise": "^0.1.4",
Useless, included in `mysql2`

2021-02-05 07:37 UTC, merged